routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\FacultyController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\InstituteDetailController;
use App\Http\Controllers\JubileeYearGalleryController;
use App\Http\Controllers\JubileeYearHistoryController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\SideNoticeController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\TopNoticeController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::get('/', [FrontendController::class, 'index']);
Route::get('/at-a-glance', [FrontendController::class, 'atAGlance']);
Route::get('/at-a-glance-bangla', [FrontendController::class, 'atAGlanceBangla']);
Route::get('/events-list', [FrontendController::class, 'events']);
Route::get('/contact', [FrontendController::class, 'contact']);
Route::get('/gallery', [FrontendController::class, 'gallery']);
Route::get('/faculty', [FrontendController::class, 'faculty']);
Route::get('/staff', [FrontendController::class, 'staff']);
Route::get('/jubilee-year-history', [FrontendController::class, 'jubileeYearHistory']);
Route::get('/jubilee-year-history-bangla', [FrontendController::class, 'jubileeYearHistoryBangla']);
Route::get('/jubilee-year-gallery', [FrontendController::class, 'jubileeYearGallery']);
Route::get('/messages/show/{message}', [MessageController::class, 'show'])->name('messages.show');
Route::get('/messages-bangla/show/{message}', [MessageController::class, 'showBangla'])->name('messages.showBangla');
Route::get('/instituteDetails/show/{instituteDetail}', [InstituteDetailController::class, 'show'])->name('instituteDetails.show');
Route::get('/instituteDetails-bangla/show/{instituteDetail}', [InstituteDetailController::class, 'showBangla'])->name('instituteDetails.showBangla');
Route::get('/events/show/{event}', [EventController::class, 'show'])->name('events.show');
Route::get('/events-bangla/show/{event}', [EventController::class, 'showBangla'])->name('events.showBangla');
// Route::get('/jubileeYearHistories/show/{jubileeYearHistory}', [JubileeYearHistoryController::class, 'show'])->name('jubileeYearHistories.show');

Route::middleware(['auth'])->group(function () {
    Route::get('/admin', [AdminController::class, 'index']);

    //user
    Route::resource('users', UserController::class);
    Route::get('/trashed-users', [UserController::class, 'trash'])->name('users.trashed');
    Route::get('/trashed-users/{user}/restore', [UserController::class, 'restore'])->name('users.restore');
    Route::delete('/trashed-users/{user}/delete', [UserController::class, 'delete'])->name('users.delete');

    //top-notice
    Route::resource('topNotices', TopNoticeController::class);
    Route::get('/topNotices/{topNotice}', [TopNoticeController::class, 'download'])->name('topNotices.download');
    Route::get('/trashed-topNotices', [TopNoticeController::class, 'trash'])->name('topNotices.trashed');
    Route::get('/trashed-topNotices/{topNotice}/restore', [TopNoticeController::class, 'restore'])->name('topNotices.restore');
    Route::delete('/trashed-topNotices/{topNotice}/delete', [TopNoticeController::class, 'delete'])->name('topNotices.delete');

    //side-notice
    Route::resource('sideNotices', SideNoticeController::class);
    Route::get('/sideNotices/{sideNotice}', [SideNoticeController::class, 'download'])->name('sideNotices.download');
    Route::get('/trashed-sideNotices', [SideNoticeController::class, 'trash'])->name('sideNotices.trashed');
    Route::get('/trashed-sideNotices/{sideNotice}/restore', [SideNoticeController::class, 'restore'])->name('sideNotices.restore');
    Route::delete('/trashed-sideNotices/{sideNotice}/delete', [SideNoticeController::class, 'delete'])->name('sideNotices.delete');

    //slider
    Route::resource('sliders', SliderController::class);
    Route::get('/sliders/{slider}', [SliderController::class, 'download'])->name('sliders.download');
    Route::get('/trashed-sliders', [SliderController::class, 'trash'])->name('sliders.trashed');
    Route::get('/trashed-sliders/{slider}/restore', [SliderController::class, 'restore'])->name('sliders.restore');
    Route::delete('/trashed-sliders/{slider}/delete', [SliderController::class, 'delete'])->name('sliders.delete');

    //messages
    Route::resource('messages', MessageController::class);
    Route::get('/messages/{message}', [MessageController::class, 'download'])->name('messages.download');
    Route::get('/trashed-messages', [MessageController::class, 'trash'])->name('messages.trashed');
    Route::get('/trashed-messages/{message}/restore', [MessageController::class, 'restore'])->name('messages.restore');
    Route::delete('/trashed-messages/{message}/delete', [MessageController::class, 'delete'])->name('messages.delete');

    //institute-details
    Route::resource('instituteDetails', InstituteDetailController::class);
    Route::get('/instituteDetails/{instituteDetail}', [InstituteDetailController::class, 'download'])->name('instituteDetails.download');
    Route::get('/trashed-instituteDetails', [InstituteDetailController::class, 'trash'])->name('instituteDetails.trashed');
    Route::get('/trashed-instituteDetails/{instituteDetail}/restore', [InstituteDetailController::class, 'restore'])->name('instituteDetails.restore');
    Route::delete('/trashed-instituteDetails/{instituteDetail}/delete', [InstituteDetailController::class, 'delete'])->name('instituteDetails.delete');

    //events
    Route::resource('events', EventController::class);
    Route::get('/events/{event}', [EventController::class, 'download'])->name('events.download');
    Route::get('/trashed-events', [EventController::class, 'trash'])->name('events.trashed');
    Route::get('/trashed-events/{event}/restore', [EventController::class, 'restore'])->name('events.restore');
    Route::delete('/trashed-events/{event}/delete', [EventController::class, 'delete'])->name('events.delete');

    //galleries
    Route::resource('galleries', GalleryController::class);
    Route::get('/galleries/{gallery}', [GalleryController::class, 'download'])->name('galleries.download');
    Route::get('/trashed-galleries', [GalleryController::class, 'trash'])->name('galleries.trashed');
    Route::get('/trashed-galleries/{gallery}/restore', [GalleryController::class, 'restore'])->name('galleries.restore');
    Route::delete('/trashed-galleries/{gallery}/delete', [GalleryController::class, 'delete'])->name('galleries.delete');

    //faculties
    Route::resource('faculties', FacultyController::class);
    Route::get('/faculties/{faculty}', [FacultyController::class, 'download'])->name('faculties.download');
    Route::get('/trashed-faculties', [FacultyController::class, 'trash'])->name('faculties.trashed');
    Route::get('/trashed-faculties/{faculty}/restore', [FacultyController::class, 'restore'])->name('faculties.restore');
    Route::delete('/trashed-faculties/{faculty}/delete', [FacultyController::class, 'delete'])->name('faculties.delete');

    //staffs
    Route::resource('staffs', StaffController::class);
    Route::get('/staffs/{staff}', [StaffController::class, 'download'])->name('staffs.download');
    Route::get('/trashed-staffs', [StaffController::class, 'trash'])->name('staffs.trashed');
    Route::get('/trashed-staffs/{staff}/restore', [StaffController::class, 'restore'])->name('staffs.restore');
    Route::delete('/trashed-staffs/{staff}/delete', [StaffController::class, 'delete'])->name('staffs.delete');

    //jubileeYearHistories
    Route::resource('jubileeYearHistories', JubileeYearHistoryController::class);
    Route::get('/jubileeYearHistories/{jubileeYearHistory}', [JubileeYearHistoryController::class, 'download'])->name('jubileeYearHistories.download');
    Route::get('/trashed-jubileeYearHistories', [JubileeYearHistoryController::class, 'trash'])->name('jubileeYearHistories.trashed');
    Route::get('/trashed-jubileeYearHistories/{jubileeYearHistory}/restore', [JubileeYearHistoryController::class, 'restore'])->name('jubileeYearHistories.restore');
    Route::delete('/trashed-jubileeYearHistories/{jubileeYearHistory}/delete', [JubileeYearHistoryController::class, 'delete'])->name('jubileeYearHistories.delete');

    //jubileeYearHistories
    Route::resource('jubileeYearGalleries', JubileeYearGalleryController::class);
    Route::get('/jubileeYearGalleries/{jubileeYearGallery}', [JubileeYearGalleryController::class, 'download'])->name('jubileeYearGalleries.download');
    Route::get('/trashed-jubileeYearGalleries', [JubileeYearHistoryControllerJubileeYearGalleryController::class, 'trash'])->name('jubileeYearGalleries.trashed');
    Route::get('/trashed-jubileeYearGalleries/{jubileeYearGallery}/restore', [JubileeYearGalleryController::class, 'restore'])->name('jubileeYearGalleries.restore');
    Route::delete('/trashed-jubileeYearGalleries/{jubileeYearGallery}/delete', [JubileeYearGalleryController::class, 'delete'])->name('jubileeYearGalleries.delete');
});

app/Models/JubileeYearGallery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class JubileeYearGallery extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = [];
}

app/Http/Controllers/JubileeYearGalleryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\JubileeYearGalleryRequest;
use App\Models\JubileeYearGallery;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class JubileeYearGalleryController extends Controller
{
    public function index()
    {
        $jubileeYearGallery = JubileeYearGallery::latest();
        if (request('search')) {
            $jubileeYearGallery = $jubileeYearGallery
                ->where('title', 'like', '%' . request('search') . '%');
        }
        $jubileeYearGalleries = $jubileeYearGallery->paginate(10);
        return view('backend.jubileeYearGalleries.index', compact('jubileeYearGalleries'));
    }
    public function create()
    {
        return view('backend.jubileeYearGalleries.create');
    }

    public function store(JubileeYearGalleryRequest $request)
    {
        try {
            $data = new JubileeYearGallery();
            $file = $request->file;
            $filename = time() . '.' . $file->getClientOriginalExtension();
            $request->file->move('assets', $filename);
            $data->file = $filename;
            $data->title = $request->title;
            $data->save();

            return redirect()->route('jubileeYearGalleries.index')->withMessage('Successfully Created!');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }
    public function download($file)
    {
        return response()->download(public_path('assets/' . $file));
    }
    public function edit($id)
    {
        $jubileeYearGallery = JubileeYearGallery::where('id', $id)->first();
        return view('backend.jubileeYearGalleries.edit', compact('jubileeYearGallery'));
    }
    public function update(JubileeYearGalleryRequest $request, $id)
    {
        try {
            JubileeYearGallery::where('id', $id)->update([
                'title' => $request->title,
            ]);

            return redirect()->route('jubileeYearGalleries.index')->withMessage('Successfully Updated!');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }
    public function destroy($id)
    {
        try {

            $jubileeYearGallery = JubileeYearGallery::where('id', $id)->first();
            $jubileeYearGallery->delete();
            return redirect()->route('jubileeYearGalleries.index')->withMessage('Successfully Deleted!');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }
    public function trash()
    {
        $jubileeYearGalleryCollection = JubileeYearGallery::onlyTrashed()->latest();
        if (request('search')) {
            $jubileeYearGalleryCollection = $jubileeYearGalleryCollection
                ->where('title', 'like', '%' . request('search') . '%');
        }
        $jubileeYearGalleries = $jubileeYearGalleryCollection->paginate(10);
        return view('backend.jubileeYearGalleries.trashed', compact('jubileeYearGalleries'));
    }
    public function restore($id)
    {
        $jubileeYearGallery = JubileeYearGallery::onlyTrashed()->findOrFail($id);
        $jubileeYearGallery->restore();
        return redirect()->route('jubileeYearGalleries.trashed')->withMessage('Successfully Restored!');
    }
    public function delete($id)
    {
        $jubileeYearGallery = JubileeYearGallery::onlyTrashed()->findOrFail($id);
        unlink(public_path('assets/' . $jubileeYearGallery->file));
        $jubileeYearGallery->forceDelete();
        return redirect()->route('jubileeYearGalleries.trashed')->withMessage('Successfully Deleted Permanently!');
    }
}

resources/views/backend/jubileeYearGalleries/create.blade.php
<x-backend.layouts.master>
    <main>
        @if (Session::has('message'))
            <div class="alert alert-success">
                {{ Session::get('message') }}
            </div>
        @endif
        <section class="section mt-5">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-8">
                    <div class="card mb-4">
                        <div class="card-header">
                            <i class="fas fa-table me-1"></i>
                            Upload Jubilee Year Image
                        </div>
                        <div class="card-body mt-3">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ route('jubileeYearGalleries.store') }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf
                                <div class="form-floating mb-3">
                                    <input class="form-control" id="title" name="title" value="{{ old('title') }}"
                                        type="text" />
                                    <label for="title">Title: (Character Limit: 30)</label>
                                    @error('title')
                                        <span class="small text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="form-floating mb-3">
                                    <input id="file" name="file" type="file" />

                                    @error('file')
                                        <span class="small text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <button class="btn btn-primary btn-block" type="submit">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
</x-backend.layouts.master>

resources/views/backend/jubileeYearGalleries/edit.blade.php
<x-backend.layouts.master>
    <main>
        @if (Session::has('message'))
            <div class="alert alert-success">
                {{ Session::get('message') }}
            </div>
        @endif
        <section class="section mt-5">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-8">
                    <div class="card mb-4">
                        <div class="card-header">
                            <i class="fas fa-table me-1"></i>
                            Update Jubilee Year Image Title
                        </div>
                        <div class="card-body mt-3">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form
                                action="{{ route('jubileeYearGalleries.update', ['jubileeYearGallery' => $jubileeYearGallery->id]) }}"
                                method="POST">
                                @csrf
                                @method('patch')
                                <div class="form-floating mb-3">
                                    <input class="form-control" id="title" name="title"
                                        value="{{ old('title', $jubileeYearGallery->title) }}" type="text" />
                                    <label for="title">Title: (Character Limit: 30)</label>
                                    @error('title')
                                        <span class="small text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <button class="btn btn-primary btn-block" type="submit">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
</x-backend.layouts.master>

resources/views/backend/jubileeYearGalleries/index.blade.php
<x-backend.layouts.master>
    <main>
        @if (Session::has('message'))
            <div class="alert alert-success">
                {{ Session::get('message') }}
            </div>
        @endif
        <section class="section mt-5">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card mb-4">
                        <div class="card-header">
                            <i class="fas fa-table me-1"></i>
                            Jubilee Year Gallery Table
                        </div>
                        <div class="card-body mt-3">
                            <div class="mt-2 mb-2">
                                <a class="btn btn-sm btn-info" href="{{ route('jubileeYearGalleries.create') }}">Add
                                    New</a>
                                <a class="btn btn-sm btn-info"
                                    href="{{ route('jubileeYearGalleries.trashed') }}">Trashed
                                    List</a>
                                <form style="display: inline" method="GET"
                                    action="{{ route('jubileeYearGalleries.index') }}">
                                    <input class="form-control float-end mb-2" style="width: 200px;" name="search"
                                        placeholder="Search Here" />
                                </form>
                            </div>
                            <table class="table table-bordered border-primary">
                                <thead>
                                    <tr>
                                        <th>Sl#</th>
                                        <th>Title</th>
                                        <th>File</th>
                                        <th>Created At</th>
                                        <th>Download</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $sl=0 @endphp
                                    @foreach ($jubileeYearGalleries as $jubileeYearGallery)
                                        <tr>
                                            <td>{{ ++$sl }}</td>
                                            <td>{{ $jubileeYearGallery->title }}</td>
                                            <td><img style="height: 80px"
                                                    src="{{ asset('') }}assets/{{ $jubileeYearGallery->file }}"
                                                    alt="{{ $jubileeYearGallery->title }}"></td>
                                            <td>{{ $jubileeYearGallery->created_at->format('d/m/y') }}</td>
                                            <td><a
                                                    href="{{ route('jubileeYearGalleries.download', ['jubileeYearGallery' => $jubileeYearGallery->file]) }}">Download</a>
                                            </td>
                                            <td>
                                                <a class="btn btn-warning btn-sm"
                                                    href="{{ route('jubileeYearGalleries.edit', ['jubileeYearGallery' => $jubileeYearGallery->id]) }}">Edit</a>
                                                <form style="display: inline;"
                                                    action="{{ route('jubileeYearGalleries.destroy', ['jubileeYearGallery' => $jubileeYearGallery->id]) }}"
                                                    method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <button onclick="return confirm('Are you want to delete?')"
                                                        class="btn btn-danger btn-sm" type="submit">Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            {{ $jubileeYearGalleries->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
</x-backend.layouts.master>

resources/views/backend/jubileeYearGalleries/trashed.blade.php
<x-backend.layouts.master>
    <main>
        @if (Session::has('message'))
            <div class="alert alert-success">
                {{ Session::get('message') }}
            </div>
        @endif
        <section class="section mt-5">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card mb-4">
                        <div class="card-header">
                            <i class="fas fa-table me-1"></i>
                            Trashed Jubilee Year Gallery Table
                        </div>
                        <div class="card-body mt-3">
                            <div class="mt-2 mb-2">
                                <a class="btn btn-sm btn-info" href="{{ route('jubileeYearGalleries.create') }}">Add
                                    New</a>
                                <a class="btn btn-sm btn-info"
                                    href="{{ route('jubileeYearGalleries.index') }}">Jubilee Year
                                    Gallery
                                    List</a>
                                <form style="display: inline" method="GET"
                                    action="{{ route('jubileeYearGalleries.trashed') }}">
                                    <input class="form-control float-end mb-2" style="width: 200px;" name="search"
                                        placeholder="Search Here" />
                                </form>
                            </div>
                            <table class="table table-bordered border-primary">
                                <thead>
                                    <tr>
                                        <th>Sl#</th>
                                        <th>Title</th>
                                        <th>File</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $sl=0 @endphp
                                    @foreach ($jubileeYearGalleries as $jubileeYearGallery)
                                        <tr>
                                            <td>{{ ++$sl }}</td>
                                            <td>{{ $jubileeYearGallery->title }}</td>
                                            <td>{{ $jubileeYearGallery->file }}</td>
                                            <td>
                                                <a class="btn btn-warning btn-sm"
                                                    href="{{ route('jubileeYearGalleries.restore', ['jubileeYearGallery' => $jubileeYearGallery->id]) }}">Restore</a>
                                                <form style="display: inline;"
                                                    action="{{ route('jubileeYearGalleries.delete', ['jubileeYearGallery' => $jubileeYearGallery->id]) }}"
                                                    method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <button
                                                        onclick="return confirm('Are you want to delete parmenently?')"
                                                        class="btn btn-danger btn-sm" type="submit">Parmanent
                                                        Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            {{ $jubileeYearGalleries->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
</x-backend.layouts.master>