routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\FacultyController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\InstituteDetailController;
use App\Http\Controllers\JubileeYearGalleryController;
use App\Http\Controllers\JubileeYearHistoryController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\SideNoticeController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\TopNoticeController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::get('/', [FrontendController::class, 'index']);
Route::get('/at-a-glance', [FrontendController::class, 'atAGlance']);
Route::get('/at-a-glance-bangla', [FrontendController::class, 'atAGlanceBangla']);
Route::get('/events-list', [FrontendController::class, 'events']);
Route::get('/contact', [FrontendController::class, 'contact']);
Route::get('/gallery', [FrontendController::class, 'gallery']);
Route::get('/faculty', [FrontendController::class, 'faculty']);
Route::get('/staff', [FrontendController::class, 'staff']);
Route::get('/jubilee-year-history', [FrontendController::class, 'jubileeYearHistory']);
Route::get('/jubilee-year-history-bangla', [FrontendController::class, 'jubileeYearHistoryBangla']);
Route::get('/jubilee-year-gallery', [FrontendController::class, 'jubileeYearGallery']);
Route::get('/messages/show/{message}', [MessageController::class, 'show'])->name('messages.show');
Route::get('/messages-bangla/show/{message}', [MessageController::class, 'showBangla'])->name('messages.showBangla');
Route::get('/instituteDetails/show/{instituteDetail}', [InstituteDetailController::class, 'show'])->name('instituteDetails.show');
Route::get('/instituteDetails-bangla/show/{instituteDetail}', [InstituteDetailController::class, 'showBangla'])->name('instituteDetails.showBangla');
Route::get('/events/show/{event}', [EventController::class, 'show'])->name('events.show');
Route::get('/events-bangla/show/{event}', [EventController::class, 'showBangla'])->name('events.showBangla');
// Route::get('/jubileeYearHistories/show/{jubileeYearHistory}', [JubileeYearHistoryController::class, 'show'])->name('jubileeYearHistories.show');

Route::middleware(['auth'])->group(function () {
    Route::get('/admin', [AdminController::class, 'index']);

    //user
    Route::resource('users', UserController::class);
    Route::get('/trashed-users', [UserController::class, 'trash'])->name('users.trashed');
    Route::get('/trashed-users/{user}/restore', [UserController::class, 'restore'])->name('users.restore');
    Route::delete('/trashed-users/{user}/delete', [UserController::class, 'delete'])->name('users.delete');

    //top-notice
    Route::resource('topNotices', TopNoticeController::class);
    Route::get('/topNotices/{topNotice}', [TopNoticeController::class, 'download'])->name('topNotices.download');
    Route::get('/trashed-topNotices', [TopNoticeController::class, 'trash'])->name('topNotices.trashed');
    Route::get('/trashed-topNotices/{topNotice}/restore', [TopNoticeController::class, 'restore'])->name('topNotices.restore');
    Route::delete('/trashed-topNotices/{topNotice}/delete', [TopNoticeController::class, 'delete'])->name('topNotices.delete');

    //side-notice
    Route::resource('sideNotices', SideNoticeController::class);
    Route::get('/sideNotices/{sideNotice}', [SideNoticeController::class, 'download'])->name('sideNotices.download');
    Route::get('/trashed-sideNotices', [SideNoticeController::class, 'trash'])->name('sideNotices.trashed');
    Route::get('/trashed-sideNotices/{sideNotice}/restore', [SideNoticeController::class, 'restore'])->name('sideNotices.restore');
    Route::delete('/trashed-sideNotices/{sideNotice}/delete', [SideNoticeController::class, 'delete'])->name('sideNotices.delete');

    //slider
    Route::resource('sliders', SliderController::class);
    Route::get('/sliders/{slider}', [SliderController::class, 'download'])->name('sliders.download');
    Route::get('/trashed-sliders', [SliderController::class, 'trash'])->name('sliders.trashed');
    Route::get('/trashed-sliders/{slider}/restore', [SliderController::class, 'restore'])->name('sliders.restore');
    Route::delete('/trashed-sliders/{slider}/delete', [SliderController::class, 'delete'])->name('sliders.delete');

    //messages
    Route::resource('messages', MessageController::class);
    Route::get('/messages/{message}', [MessageController::class, 'download'])->name('messages.download');
    Route::get('/trashed-messages', [MessageController::class, 'trash'])->name('messages.trashed');
    Route::get('/trashed-messages/{message}/restore', [MessageController::class, 'restore'])->name('messages.restore');
    Route::delete('/trashed-messages/{message}/delete', [MessageController::class, 'delete'])->name('messages.delete');

    //institute-details
    Route::resource('instituteDetails', InstituteDetailController::class);
    Route::get('/instituteDetails/{instituteDetail}', [InstituteDetailController::class, 'download'])->name('instituteDetails.download');
    Route::get('/trashed-instituteDetails', [InstituteDetailController::class, 'trash'])->name('instituteDetails.trashed');
    Route::get('/trashed-instituteDetails/{instituteDetail}/restore', [InstituteDetailController::class, 'restore'])->name('instituteDetails.restore');
    Route::delete('/trashed-instituteDetails/{instituteDetail}/delete', [InstituteDetailController::class, 'delete'])->name('instituteDetails.delete');

    //events
    Route::resource('events', EventController::class);
    Route::get('/events/{event}', [EventController::class, 'download'])->name('events.download');
    Route::get('/trashed-events', [EventController::class, 'trash'])->name('events.trashed');
    Route::get('/trashed-events/{event}/restore', [EventController::class, 'restore'])->name('events.restore');
    Route::delete('/trashed-events/{event}/delete', [EventController::class, 'delete'])->name('events.delete');

    //galleries
    Route::resource('galleries', GalleryController::class);
    Route::get('/galleries/{gallery}', [GalleryController::class, 'download'])->name('galleries.download');
    Route::get('/trashed-galleries', [GalleryController::class, 'trash'])->name('galleries.trashed');
    Route::get('/trashed-galleries/{gallery}/restore', [GalleryController::class, 'restore'])->name('galleries.restore');
    Route::delete('/trashed-galleries/{gallery}/delete', [GalleryController::class, 'delete'])->name('galleries.delete');

    //faculties
    Route::resource('faculties', FacultyController::class);
    Route::get('/faculties/{faculty}', [FacultyController::class, 'download'])->name('faculties.download');
    Route::get('/trashed-faculties', [FacultyController::class, 'trash'])->name('faculties.trashed');
    Route::get('/trashed-faculties/{faculty}/restore', [FacultyController::class, 'restore'])->name('faculties.restore');
    Route::delete('/trashed-faculties/{faculty}/delete', [FacultyController::class, 'delete'])->name('faculties.delete');

    //staffs
    Route::resource('staffs', StaffController::class);
    Route::get('/staffs/{staff}', [StaffController::class, 'download'])->name('staffs.download');
    Route::get('/trashed-staffs', [StaffController::class, 'trash'])->name('staffs.trashed');
    Route::get('/trashed-staffs/{staff}/restore', [StaffController::class, 'restore'])->name('staffs.restore');
    Route::delete('/trashed-staffs/{staff}/delete', [StaffController::class, 'delete'])->name('staffs.delete');

    //jubileeYearHistories
    Route::resource('jubileeYearHistories', JubileeYearHistoryController::class);
    Route::get('/jubileeYearHistories/{jubileeYearHistory}', [JubileeYearHistoryController::class, 'download'])->name('jubileeYearHistories.download');
    Route::get('/trashed-jubileeYearHistories', [JubileeYearHistoryController::class, 'trash'])->name('jubileeYearHistories.trashed');
    Route::get('/trashed-jubileeYearHistories/{jubileeYearHistory}/restore', [JubileeYearHistoryController::class, 'restore'])->name('jubileeYearHistories.restore');
    Route::delete('/trashed-jubileeYearHistories/{jubileeYearHistory}/delete', [JubileeYearHistoryController::class, 'delete'])->name('jubileeYearHistories.delete');

    //jubileeYearHistories
    Route::resource('jubileeYearGalleries', JubileeYearGalleryController::class);
    Route::get('/jubileeYearGalleries/{jubileeYearGallery}', [JubileeYearGalleryController::class, 'download'])->name('jubileeYearGalleries.download');
    Route::get('/trashed-jubileeYearGalleries', [JubileeYearHistoryControllerJubileeYearGalleryController::class, 'trash'])->name('jubileeYearGalleries.trashed');
    Route::get('/trashed-jubileeYearGalleries/{jubileeYearGallery}/restore', [JubileeYearGalleryController::class, 'restore'])->name('jubileeYearGalleries.restore');
    Route::delete('/trashed-jubileeYearGalleries/{jubileeYearGallery}/delete', [JubileeYearGalleryController::class, 'delete'])->name('jubileeYearGalleries.delete');
});

app/Models/Faculty.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Faculty extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = [];
}

app/Http/Controllers/FacultyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\FacultyRequest;
use App\Models\Faculty;
use Illuminate\Database\QueryException;

class FacultyController extends Controller
{
    public function index()
    {
        $faculty = Faculty::latest();
        if (request('search')) {
            $faculty = $faculty
                ->where('name', 'like', '%' . request('search') . '%');
        }
        $faculties = $faculty->paginate(10);
        return view('backend.faculties.index', compact('faculties'));
    }
    public function create()
    {
        return view('backend.faculties.create');
    }

    public function store(FacultyRequest $request)
    {
        try {
            $data = new Faculty();
            $file = $request->file;
            $filename = time() . '.' . $file->getClientOriginalExtension();
            $request->file->move('assets', $filename);
            $data->file = $filename;
            $data->name = $request->name;
            $data->mobile = $request->mobile;
            $data->save();

            return redirect()->route('faculties.index')->withMessage('Successfully Created!');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }
    public function download($file)
    {
        return response()->download(public_path('assets/' . $file));
    }
    public function edit($id)
    {
        $faculty = Faculty::where('id', $id)->first();
        return view('backend.faculties.edit', compact('faculty'));
    }
    public function update(FacultyRequest $request, $id)
    {
        try {
            Faculty::where('id', $id)->update([
                'name' => $request->name,
                'mobile' => $request->mobile,
            ]);

            return redirect()->route('faculties.index')->withMessage('Successfully Updated!');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }
    public function destroy($id)
    {
        try {

            $faculty = Faculty::where('id', $id)->first();
            $faculty->delete();
            return redirect()->route('faculties.index')->withMessage('Successfully Deleted!');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }
    public function trash()
    {
        $facultyCollection = Faculty::onlyTrashed()->latest();
        if (request('search')) {
            $facultyCollection = $facultyCollection
                ->where('name', 'like', '%' . request('search') . '%');
        }
        $faculties = $facultyCollection->paginate(10);
        return view('backend.faculties.trashed', compact('faculties'));
    }
    public function restore($id)
    {
        $faculty = Faculty::onlyTrashed()->findOrFail($id);
        $faculty->restore();
        return redirect()->route('faculties.trashed')->withMessage('Successfully Restored!');
    }
    public function delete($id)
    {
        $faculty = Faculty::onlyTrashed()->findOrFail($id);
        unlink(public_path('assets/' . $faculty->file));
        $faculty->forceDelete();
        return redirect()->route('faculties.trashed')->withMessage('Successfully Deleted Permanently!');
    }
}

resources/views/backend/faculties/create.blade.php
<x-backend.layouts.master>
    <main>
        @if (Session::has('message'))
            <div class="alert alert-success">
                {{ Session::get('message') }}
            </div>
        @endif
        <section class="section mt-5">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-8">
                    <div class="card mb-4">
                        <div class="card-header">
                            <i class="fas fa-table me-1"></i>
                            Upload Faculty Information
                        </div>
                        <div class="card-body mt-3">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ route('faculties.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="form-floating mb-3">
                                    <input class="form-control" id="name" name="name" value="{{ old('name') }}"
                                        type="text" />
                                    <label for="name">Name: (Character Limit: 30)</label>
                                    @error('name')
                                        <span class="small text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="form-floating mb-3">
                                    <input class="form-control" id="mobile" name="mobile"
                                        value="{{ old('mobile') }}" type="text" />
                                    <label for="mobile">Mobile: (Character Limit: 11)</label>
                                    @error('mobile')
                                        <span class="small text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="form-floating mb-3">
                                    <input id="file" name="file" type="file" />

                                    @error('file')
                                        <span class="small text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <button class="btn btn-primary btn-block" type="submit">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
</x-backend.layouts.master>

resources/views/backend/faculties/edit.blade.php
<x-backend.layouts.master>
    <main>
        @if (Session::has('message'))
            <div class="alert alert-success">
                {{ Session::get('message') }}
            </div>
        @endif
        <section class="section mt-5">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-8">
                    <div class="card mb-4">
                        <div class="card-header">
                            <i class="fas fa-table me-1"></i>
                            Update Faculty Information
                        </div>
                        <div class="card-body mt-3">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ route('faculties.update', ['faculty' => $faculty->id]) }}" method="POST">
                                @csrf
                                @method('patch')
                                <div class="form-floating mb-3">
                                    <input class="form-control" id="name" name="name"
                                        value="{{ old('name', $faculty->name) }}" type="text" />
                                    <label for="name">Name: (Character Limit: 30)</label>
                                    @error('name')
                                        <span class="small text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="form-floating mb-3">
                                    <input class="form-control" id="mobile" name="mobile"
                                        value="{{ old('mobile', $faculty->mobile) }}" type="text" />
                                    <label for="name">Mobile: (Character Limit: 11)</label>
                                    @error('name')
                                        <span class="small text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <button class="btn btn-primary btn-block" type="submit">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
</x-backend.layouts.master>

resources/views/backend/faculties/index.blade.php
<x-backend.layouts.master>
    <main>
        @if (Session::has('message'))
            <div class="alert alert-success">
                {{ Session::get('message') }}
            </div>
        @endif
        <section class="section mt-5">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card mb-4">
                        <div class="card-header">
                            <i class="fas fa-table me-1"></i>
                            Faculty Information Table
                        </div>
                        <div class="card-body mt-3">
                            <div class="mt-2 mb-2">
                                <a class="btn btn-sm btn-info" href="{{ route('faculties.create') }}">Add New</a>
                                <a class="btn btn-sm btn-info" href="{{ route('faculties.trashed') }}">Trashed
                                    List</a>
                                <form style="display: inline" method="GET" action="{{ route('faculties.index') }}">
                                    <input class="form-control float-end mb-2" style="width: 200px;" name="search"
                                        placeholder="Search Here" />
                                </form>
                            </div>
                            <table class="table table-bordered border-primary">
                                <thead>
                                    <tr>
                                        <th>Sl#</th>
                                        <th>Name</th>
                                        <th>Mobile</th>
                                        <th>File</th>
                                        <th>Created At</th>
                                        <th>Download</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $sl=0 @endphp
                                    @foreach ($faculties as $faculty)
                                        <tr>
                                            <td>{{ ++$sl }}</td>
                                            <td>{{ $faculty->name }}</td>
                                            <td>{{ $faculty->mobile }}</td>
                                            <td><img style="height: 80px"
                                                    src="{{ asset('') }}assets/{{ $faculty->file }}"
                                                    alt="{{ $faculty->title }}"></td>
                                            <td>{{ $faculty->created_at->format('d/m/y') }}</td>
                                            <td><a
                                                    href="{{ route('faculties.download', ['faculty' => $faculty->file]) }}">Download</a>
                                            </td>
                                            <td>
                                                <a class="btn btn-warning btn-sm"
                                                    href="{{ route('faculties.edit', ['faculty' => $faculty->id]) }}">Edit</a>
                                                <form style="display: inline;"
                                                    action="{{ route('faculties.destroy', ['faculty' => $faculty->id]) }}"
                                                    method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <button onclick="return confirm('Are you want to delete?')"
                                                        class="btn btn-danger btn-sm" type="submit">Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            {{ $faculties->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
</x-backend.layouts.master>

resources/views/backend/faculties/trashed.blade.php
<x-backend.layouts.master>
    <main>
        @if (Session::has('message'))
            <div class="alert alert-success">
                {{ Session::get('message') }}
            </div>
        @endif
        <section class="section mt-5">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card mb-4">
                        <div class="card-header">
                            <i class="fas fa-table me-1"></i>
                            Trashed Faculty Information Table
                        </div>
                        <div class="card-body mt-3">
                            <div class="mt-2 mb-2">
                                <a class="btn btn-sm btn-info" href="{{ route('faculties.create') }}">Add New</a>
                                <a class="btn btn-sm btn-info" href="{{ route('faculties.index') }}">Faculty
                                    List</a>
                                <form style="display: inline" method="GET" action="{{ route('faculties.trashed') }}">
                                    <input class="form-control float-end mb-2" style="width: 200px;" name="search"
                                        placeholder="Search Here" />
                                </form>
                            </div>
                            <table class="table table-bordered border-primary">
                                <thead>
                                    <tr>
                                        <th>Sl#</th>
                                        <th>Name</th>
                                        <th>Mobile</th>
                                        <th>File</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $sl=0 @endphp
                                    @foreach ($faculties as $faculty)
                                        <tr>
                                            <td>{{ ++$sl }}</td>
                                            <td>{{ $faculty->name }}</td>
                                            <td>{{ $faculty->mobile }}</td>
                                            <td>{{ $faculty->file }}</td>
                                            <td>
                                                <a class="btn btn-warning btn-sm"
                                                    href="{{ route('faculties.restore', ['faculty' => $faculty->id]) }}">Restore</a>
                                                <form style="display: inline;"
                                                    action="{{ route('faculties.delete', ['faculty' => $faculty->id]) }}"
                                                    method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <button
                                                        onclick="return confirm('Are you want to delete parmenently?')"
                                                        class="btn btn-danger btn-sm" type="submit">Parmanent
                                                        Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            {{ $faculties->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
</x-backend.layouts.master>